# Generated by Django 2.2.17 on 2021-03-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
