# Generated by Django 2.2.17 on 2021-04-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210402_2008'),
        ('store', '0014_auto_20210404_1411'),
    ]

    operations = [
    ]
