# Generated by Django 2.2.17 on 2021-04-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_merge_20210404_1638'),
        ('store', '0017_merge_20210404_1736'),
    ]

    operations = [
    ]
